source 'http://rubygems.org'

gem 'sinatra'
gem 'activerecord', :require => 'active_record'
gem 'sinatra-activerecord', :require => 'sinatra/activerecord'
gem 'rake'
gem 'require_all'
gem 'pg'
# gem 'sqlite3'
gem 'thin'
gem 'pry'
gem 'bcrypt'
gem "tux"
gem 'shotgun'
gem 'pry-byebug'